{{- if .Values.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.configmap.variables }}
  {{ $key | toYaml }}: {{ $value | quote }}
{{- end }}
{{- end }}
