---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "helpers.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        {{- include "helpers.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.image.pullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Release.Name }}-image-pull
    {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- if .Values.probes.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessPath }}
            port: {{ .Values.service.port }}
{{ toYaml .Values.probes.liveness | indent 10 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessPath }}
            port: {{ .Values.service.port }}
{{ toYaml .Values.probes.readiness | indent 10 }}
    {{- end }}
      {{- if .Values.configmap.enabled }}
        env:
          {{- include "helpers.list-env-variables" . | indent 8 }}
      {{- end }}
